
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label label2;

	private global::Gtk.Entry sueldoBaseEntry;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Label label3;

	private global::Gtk.Entry cantHijosEntry;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Button calcularSueldoBtn;

	private global::Gtk.Entry nuevoSueldoEntry;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Button button1;

	private global::Gtk.Button button2;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 5;
		this.vbox1.BorderWidth = ((uint)(8));
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Sueldo Base:");
		this.hbox1.Add(this.label2);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label2]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.sueldoBaseEntry = new global::Gtk.Entry();
		this.sueldoBaseEntry.CanFocus = true;
		this.sueldoBaseEntry.Name = "sueldoBaseEntry";
		this.sueldoBaseEntry.IsEditable = true;
		this.sueldoBaseEntry.InvisibleChar = '•';
		this.hbox1.Add(this.sueldoBaseEntry);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.sueldoBaseEntry]));
		w2.Position = 1;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Cantidad hijos:");
		this.hbox2.Add(this.label3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label3]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.cantHijosEntry = new global::Gtk.Entry();
		this.cantHijosEntry.CanFocus = true;
		this.cantHijosEntry.Name = "cantHijosEntry";
		this.cantHijosEntry.IsEditable = true;
		this.cantHijosEntry.InvisibleChar = '•';
		this.hbox2.Add(this.cantHijosEntry);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.cantHijosEntry]));
		w5.Position = 1;
		this.vbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.calcularSueldoBtn = new global::Gtk.Button();
		this.calcularSueldoBtn.Sensitive = false;
		this.calcularSueldoBtn.CanFocus = true;
		this.calcularSueldoBtn.Name = "calcularSueldoBtn";
		this.calcularSueldoBtn.UseUnderline = true;
		this.calcularSueldoBtn.Label = global::Mono.Unix.Catalog.GetString("Calcular Nuevo Sueldo");
		this.hbox3.Add(this.calcularSueldoBtn);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.calcularSueldoBtn]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.nuevoSueldoEntry = new global::Gtk.Entry();
		this.nuevoSueldoEntry.CanFocus = true;
		this.nuevoSueldoEntry.Name = "nuevoSueldoEntry";
		this.nuevoSueldoEntry.IsEditable = false;
		this.nuevoSueldoEntry.InvisibleChar = '•';
		this.hbox3.Add(this.nuevoSueldoEntry);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.nuevoSueldoEntry]));
		w8.Position = 1;
		this.vbox1.Add(this.hbox3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Limpiar");
		this.hbox4.Add(this.button1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.button1]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("Salir");
		this.hbox4.Add(this.button2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.button2]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		this.vbox1.Add(this.hbox4);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
		w12.Position = 3;
		w12.Expand = false;
		w12.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.sueldoBaseEntry.Changed += new global::System.EventHandler(this.OnSueldoBaseChanged);
		this.cantHijosEntry.Changed += new global::System.EventHandler(this.OnCantHijosChanged);
		this.calcularSueldoBtn.Clicked += new global::System.EventHandler(this.CalcularNuevoSueldo);
		this.button1.Clicked += new global::System.EventHandler(this.OnLimpiar);
		this.button2.Clicked += new global::System.EventHandler(this.OnSalirClicked);
	}
}
